//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zefitret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeciesDataTable
    {
        public int SId { get; set; }
        public string Category { get; set; }
        public string SName { get; set; }
        public string LocalName { get; set; }
        public string CommonName { get; set; }
        public string Description { get; set; }
        public byte[] MainPic { get; set; }
        public string FileNameMain { get; set; }
        public byte[] SecPic { get; set; }
        public string FileNameSecond { get; set; }
        public byte[] ThirdPic { get; set; }
        public byte[] FourthPic { get; set; }
        public string PicTakenBy { get; set; }
        public string ContentBy { get; set; }
        public string EditedBy { get; set; }
    }
}
